os: linux
arch:
    - s390x

language: php

php:
    - 8.0

env:
    - XDEBUG_MODE=coverage

before_install:
    - pecl channel-update pecl.php.net
    - pecl install -f mongodb

before_script:
    - composer install --dev --no-interaction

script:
    - ./vendor/bin/phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash)
  
