language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - pecl install mongodb

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --debug || RESULT=$?