language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - APCU_VERSION=4.0.11
  - APCU_VERSION=5.1.8
  - APCU_VERSION=5.1.11

matrix:
  exclude:
    - php : 5.6
      env : APCU_VERSION=5.1.8
    - php : 5.6
      env : APCU_VERSION=5.1.11
    - php : 7.0
      env : APCU_VERSION=4.0.11
    - php : 7.1
      env : APCU_VERSION=4.0.11


before_install:
  - pecl channel-update pecl.php.net
  - pecl install -f mongodb
  - yes '' | pecl install -f apcu-${APCU_VERSION}

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --debug